### ISSUE TITLE
buildpack is failing to install CLI with ModuleNotFoundError: No module named 'pip._internal'

### ISSUE THREAD

**Issue by chdsbd** [heroku/heroku-buildpack-awscli#10]
```
-----> AWS CLI app detected
-----> Installing AWS CLI
       Running cmd: /app/.heroku/python/bin/python virtualenv.py --no-download --python /app/.heroku/python/bin/python /app/.awscli
       Running cmd: /app/.awscli/bin/pip install --no-binary :all: --no-cache-dir --no-index --find-links file://. setuptools_scm-3.3.3.tar.gz
       Traceback (most recent call last):
         File "/tmp/build_f27eb55f2fee6100ee0ef83c1f744b20/.awscli/awscli-bundle/install", line 223, in <module>
           main()
         File "/tmp/build_f27eb55f2fee6100ee0ef83c1f744b20/.awscli/awscli-bundle/install", line 205, in main
           pip_install_packages(opts.install_dir)
         File "/tmp/build_f27eb55f2fee6100ee0ef83c1f744b20/.awscli/awscli-bundle/install", line 151, in pip_install_packages
           _install_setup_deps(pip_script, '.')
         File "/tmp/build_f27eb55f2fee6100ee0ef83c1f744b20/.awscli/awscli-bundle/install", line 168, in _install_setup_deps
           pip_script, setup_package_dir, setuptools_scm_tarball))
         File "/tmp/build_f27eb55f2fee6100ee0ef83c1f744b20/.awscli/awscli-bundle/install", line 66, in run
           p.returncode, cmd, output))
       __main__.BadRCError: Bad rc (1) for cmd '/app/.awscli/bin/pip install --no-binary :all: --no-cache-dir --no-index --find-links file://. setuptools_scm-3.3.3.tar.gz': Traceback (most recent call last):
         File "/app/.awscli/bin/pip", line 5, in <module>
           from pip._internal.main import main
       ModuleNotFoundError: No module named 'pip._internal'
```

**Comment by vaisakhpisharody** [comment]
Is this issue resolved?
If not, I assume you are using Pipfile for installing your dependencies?

It seems like this buildpack needs us to use requirements.txt for installing dependencies.
I had the same issue before but got it working, once I moved my dependencies over to `requirements.txt`

**Comment by edmorley** [comment]
Closing since it seems like this is resolved.
